include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - package_api_docs
    - test_types_in_equals
    - use_super_parameters
